services:

  vnc:
    build:
      context: .
      dockerfile: ./Dockerfile

    image: bisos_deb13-fresh:latest
    container_name: bisos_deb13-fresh

    volumes:
       - ./:/shuttle/this
       # - /var/bisos/docker/:/shuttle/var

    # restart: no

    ports:
      - "2227:22"    # SSH
      - "5906:5901"    # VNC
      - "6906:6901"    # NoVNC

# Just run:: docker compose up -d
