services:

  desktop:
    build:
      context: .
      dockerfile: ./Dockerfile

    image: bisos/deb13-fresh-vnc-xfce:4
    container_name: mb-deb13-fresh-xfce-4

    volumes:
       - ./:/shuttle/this
       # - /var/bisos/docker/:/shuttle/var

    # restart: no

    ports:
      - "2222:22"    # SSH
      - "5901:5901"    # VNC
      - "6901:6901"    # NoVNC

# Just run:: docker compose up -d
