version: '2.0'

services:

  web:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    image: deb-12-novnc-xfce-enpsx:l
    container_name: mbanan3_enpsx_big

    command: bash -c "tail -F /dev/null"        
    volumes:
      - .:/code
      - /tmp:/tmp
      - /etc/localtime:/etc/localtime:ro
      - ./filestore:/filestore
    restart: no

    ports:
      #- "8022:8022"  # Your Django app port
      - "8816:8016"  # Your Django app port
      - "2222:22"    # SSH
      - "5901:5901"    # VNC
      - "6901:6901"    # NoVNC

# to start
#docker-compose up -d

