services:

  vnc:
    build:
      context: .
      dockerfile: ./Dockerfile

    image: bisos_deb12-fresh:latest
    container_name: bisos_deb12-fresh

    pids_limit: 16384

    volumes:
       - ./:/shuttle/this
       # - /var/bisos/docker/:/shuttle/var

    # restart: no

    ports:
      - "2222:22"    # SSH
      - "5901:5901"    # VNC
      - "6901:6901"    # NoVNC

# Just run:: docker compose up -d
