services:

  vnc:
    build:
      context: .
      dockerfile: ./Dockerfile

    image: bisos_deb12-sysd:latest
    container_name: bisos_deb12-sysd

    privileged: true
    pids_limit: -1
    cgroup: host

    volumes:
       - ./:/shuttle/this
       - /sys/fs/cgroup:/sys/fs/cgroup:rw
       - /sys/fs/fuse:/sys/fs/fuse
    tmpfs:
      - /tmp
      - /run
      - /run/lock
      - /var/log/journal

    stop_signal: SIGRTMIN+3

    ports:
      - "2223:22"      # SSH
      - "5902:5901"    # VNC
      - "6902:6901"    # NoVNC

# Just run:: docker compose up -d
